version: '3.1'
services:
    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
            interval: 10s
            start_period: 10s
        command: ['--replSet', 'test-rs', '--bind_ip_all']
    redis:
        image: redis:6-alpine
        restart: always
        ports:
            - 6379:6379
    redis-commander:
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8082:8081'
